const currencyNames = {
  aed: "United Arab Emirates Dirham",
  afn: "Afghan Afghani",
  all: "Albanian Lek",
  amd: "Armenian Dram",
  ang: "Netherlands Antillean Guilder",
  aoa: "Angolan Kwanza",
  ars: "Argentine Peso",
  aud: "Australian Dollar",
  awg: "Aruban Florin",
  azn: "Azerbaijani Manat",
  bam: "Bosnia-Herzegovina Convertible Mark",
  bbd: "Barbadian Dollar",
  bdt: "Bangladeshi Taka",
  bgn: "Bulgarian Lev",
  bhd: "Bahraini Dinar",
  bif: "Burundian Franc",
  bmd: "Bermudian Dollar",
  bnd: "Brunei Dollar",
  bob: "Bolivian Boliviano",
  brl: "Brazilian Real",
  bsd: "Bahamian Dollar",
  btn: "Bhutanese Ngultrum",
  bwp: "Botswana Pula",
  byn: "Belarusian Ruble",
  bzd: "Belize Dollar",
  cad: "Canadian Dollar",
  cdf: "Congolese Franc",
  chf: "Swiss Franc",
  clp: "Chilean Peso",
  cny: "Chinese Yuan",
  cop: "Colombian Peso",
  crc: "Costa Rican Colón",
  cup: "Cuban Peso",
  cve: "Cape Verdean Escudo",
  czk: "Czech Koruna",
  djf: "Djiboutian Franc",
  dkk: "Danish Krone",
  dop: "Dominican Peso",
  dzd: "Algerian Dinar",
  egp: "Egyptian Pound",
  ern: "Eritrean Nakfa",
  etb: "Ethiopian Birr",
  eur: "Euro",
  fjd: "Fijian Dollar",
  fkp: "Falkland Islands Pound",
  gbp: "British Pound Sterling",
  gel: "Georgian Lari",
  ghs: "Ghanaian Cedi",
  gip: "Gibraltar Pound",
  gmd: "Gambian Dalasi",
  gnf: "Guinean Franc",
  gtq: "Guatemalan Quetzal",
  gyd: "Guyanese Dollar",
  hkd: "Hong Kong Dollar",
  hnl: "Honduran Lempira",
  hrk: "Croatian Kuna",
  htg: "Haitian Gourde",
  huf: "Hungarian Forint",
  idr: "Indonesian Rupiah",
  ils: "Israeli New Shekel",
  inr: "Indian Rupee",
  iqd: "Iraqi Dinar",
  irr: "Iranian Rial",
  isk: "Icelandic Króna",
  jmd: "Jamaican Dollar",
  jod: "Jordanian Dinar",
  jpy: "Japanese Yen",
  kes: "Kenyan Shilling",
  kgs: "Kyrgystani Som",
  khr: "Cambodian Riel",
  kmf: "Comorian Franc",
  kpw: "North Korean Won",
  krw: "South Korean Won",
  kwd: "Kuwaiti Dinar",
  kyd: "Cayman Islands Dollar",
  kzt: "Kazakhstani Tenge",
  lak: "Laotian Kip",
  lbp: "Lebanese Pound",
  lkr: "Sri Lankan Rupee",
  lrd: "Liberian Dollar",
  lsl: "Lesotho Loti",
  ltl: "Lithuanian Litas",
  lvl: "Latvian Lats",
  lyd: "Libyan Dinar",
  mad: "Moroccan Dirham",
  mdl: "Moldovan Leu",
  mga: "Malagasy Ariary",
  mkd: "Macedonian Denar",
  mmk: "Myanmar Kyat",
  mnt: "Mongolian Tögrög",
  mop: "Macanese Pataca",
  mru: "Mauritanian Ouguiya",
  mur: "Mauritian Rupee",
  mvr: "Maldivian Rufiyaa",
  mwk: "Malawian Kwacha",
  mxn: "Mexican Peso",
  myr: "Malaysian Ringgit",
  mzn: "Mozambican Metical",
  nad: "Namibian Dollar",
  ngn: "Nigerian Naira",
  nio: "Nicaraguan Córdoba",
  nok: "Norwegian Krone",
  npr: "Nepalese Rupee",
  nzd: "New Zealand Dollar",
  omr: "Omani Rial",
  pab: "Panamanian Balboa",
  pen: "Peruvian Sol",
  pgk: "Papua New Guinean Kina",
  php: "Philippine Peso",
  pkr: "Pakistani Rupee",
  pln: "Polish Złoty",
  pyg: "Paraguayan Guaraní",
  qar: "Qatari Rial",
  ron: "Romanian Leu",
  rsd: "Serbian Dinar",
  rub: "Russian Ruble",
  rwf: "Rwandan Franc",
  sar: "Saudi Riyal",
  sbd: "Solomon Islands Dollar",
  scr: "Seychellois Rupee",
  sdg: "Sudanese Pound",
  sek: "Swedish Krona",
  sgd: "Singapore Dollar",
  shp: "Saint Helena Pound",
  sll: "Sierra Leonean Leone",
  sos: "Somali Shilling",
  srd: "Surinamese Dollar",
  ssp: "South Sudanese Pound",
  std: "São Tomé and Príncipe Dobra",
  svc: "Salvadoran Colón",
  syp: "Syrian Pound",
  szl: "Swazi Lilangeni",
  thb: "Thai Baht",
  tjs: "Tajikistani Somoni",
  tmt: "Turkmenistani Manat",
  tnd: "Tunisian Dinar",
  top: "Tongan Paʻanga",
  try: "Turkish Lira",
  ttd: "Trinidad and Tobago Dollar",
  twd: "New Taiwan Dollar",
  tzs: "Tanzanian Shilling",
  uah: "Ukrainian Hryvnia",
  ugx: "Ugandan Shilling",
  usd: "US Dollar",
  uyu: "Uruguayan Peso",
  uzs: "Uzbekistani Soʻm",
  ves: "Venezuelan Bolívar",
  vnd: "Vietnamese Đồng",
  vuv: "Vanuatu Vatu",
  wst: "Samoan Tala",
  xaf: "Central African CFA Franc",
  xcd: "East Caribbean Dollar",
  xof: "West African CFA Franc",
  xpf: "CFP Franc",
  yer: "Yemeni Rial",
  zar: "South African Rand",
  zmw: "Zambian Kwacha",
  zwl: "Zimbabwean Dollar",

  // Crypto
  btc: "Bitcoin",
  eth: "Ethereum",
  bnb: "Binance Coin",
  ada: "Cardano",
  xrp: "Ripple",
  doge: "Dogecoin",
  dot: "Polkadot",
  ltc: "Litecoin",
  link: "Chainlink",
  sol: "Solana",
  uni: "Uniswap",
  matic: "Polygon",
  avax: "Avalanche",
  xlm: "Stellar",
  atom: "Cosmos",
  shib: "Shiba Inu",
  trx: "TRON",
  etc: "Ethereum Classic",
  ftm: "Fantom",
  algo: "Algorand",
  near: "NEAR Protocol",
  sand: "The Sandbox",
  mana: "Decentraland",
  aave: "Aave",
  axs: "Axie Infinity",
  crv: "Curve DAO Token",
  dai: "Dai",
  busd: "Binance USD",
  usdt: "Tether",
  usdc: "USD Coin",
  luna: "Terra",
  qnt: "Quant",
  rune: "THORChain",
  icp: "Internet Computer",
  egld: "MultiversX",
  hnt: "Helium",
  gala: "Gala",
  kava: "Kava",
  kas: "Kaspa",
  sui: "Sui",
  op: "Optimism",
  arb: "Arbitrum",
  imx: "Immutable X",
  rpl: "Rocket Pool",
  render: "Render Token",
  pepe: "Pepe Coin",
};

const funnyNames = [
  "Financial Goblin Juice 💰🧃",
  "RizzCoin™ 😎",
  "Mystery Token 🔮",
  "Uncertified MemeMoni 💀",
  "Dangerous Dust ✨",
  "Scam Likely 📞",
  "Internet Beans 🫘",
  "Based Currency 💅",
  "Possibly Illegal 💼",
  "Moon Or Doom 🚀💥",

  // 🔥 New Additions
  "Tax Evasion Token 🧾",
  "Literal Monopoly Money 🎲",
  "Crypto of Shame 😔",
  "HODL & Cry 💦",
  "Zero Utility Guaranteed 🔥",
  "Rugged Since Birth 🪤",
  "MemeFi v2 💫",
  "Gas Fee Collector ⛽",
  "Certified Exit Scam 🧯",
  "DeFi Degenerate 📉",
  "Your Ex’s Investment 🥀",
  "Backed By Vibes™ 🌀",
  "404: Value Not Found ❌",
  "Lambo Dreams Delayed 🏎️",
  "Govt-Watchlisted 💀📋",
  "Under Investigation 🕵️‍♂️",
  "Not Legal Tender 🧨",
  "Social Token of Clowns 🤡",
  "Ponzi+ Plus Max Pro™ 📊",
  "Web3 Wasteland ☢️",
  "Unforkable Fork 🔪",
  "Fully Diluted Copium 🫠",
  "Definitely Not a Scam 👀",
  "Rugpull Simulator 2025 🧶",
  "Temporarily Valuable™ 🧠",
  "The Chosen Token ⚔️",
  "Made With ChatGPT 😇",
  "AirDropped Depression 😵‍💫",
];

export { currencyNames, funnyNames };
